dataset_name: EgoPER
train_split: training
val_split: validation
test_split: test
model_name: LocPointTransformer_GMM_CAUSAL_SMOOTH_GCN
devices: ['cuda:1']
dataset: {num_classes: 9, trunc_thresh: 0.5, crop_ratio: [0.9, 1.0], max_seq_len: 2304,
  background_ratio: 1.0, use_gcn: true, task: quesadilla}
model: {
  num_components: 2,
  fpn_type: identity, 
  backbone_type: convGCNTransformer,
  gcn_type: GCN, 
  max_buffer_len_factor: 6.0, 
  n_mha_win_size: 19,
  smooth_type: gaussian,
  sigma: 4,
  task_graph_nodes: 13,
  task_name: quesadilla,
}
opt: {
  learning_rate: 0.001,
  epochs: 200,
  weight_decay: 0.05, 
  schedule_gamma: 0.7
}
loader: { batch_size: 1 }
train_cfg: { init_loss_norm: 100, clip_grad_l2norm: 1.0, cls_prior_prob: 0.01, center_sample: radius,
  gmm: true, center_sample_radius: 1.5 }
test_cfg: {
  voting_thresh: 0.7, pre_nms_topk: 2000, max_seg_num: 200, min_score: 0.001,
  multiclass_nms: true,
  DMAP_backbone_enable: true,
  DMAP_backbone_stage: ['stem', 'branch'],          
  DMAP_backbone_indices: [],          
  DMAP_mini_batch_size: 64,           
  DMAP_rope_theta: 10000,             
  DMAP_stage_kind: encoder,            
  DMAP_gcn_window_size: 128         
}
output_folder: ./ckpt/EgoPER_online_tcml_taskgraph/
